version: "3.9"

services:
  app:
    build: .
    container_name: smartstock_app
    ports:
      - "8000:80"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/var/www/html
      - ./public/build:/var/www/html/public/build

  db:
    image: postgres:15
    container_name: smartstock_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
